### ISSUE TITLE
怎样导入使用呢

### ISSUE THREAD

**Issue by bloodNeverCold** [rrrfff/AndHook#14]
小白问一个很傻的 问题 是将 AndHook这个类 和so文件导入项目中 就可以使用了吗

**Comment by rrrfff** [comment]
是的

**Comment by bloodNeverCold** [comment]
大神 放进项目里面 虚拟机5.1崩溃了  手机6.0 5.1都能适应 
11-15 16:34:16.407 5130-5130/com.ct.plat.android.ZhiFuSecurity E/AndHook: failed to locate android runtime /system/lib/libart.so!
11-15 16:34:16.407 5130-5130/com.ct.plat.android.ZhiFuSecurity E/AndHook: incompatible sdk platform 22 or libhoudini environment!
11-15 16:34:16.408 5130-5130/com.ct.plat.android.ZhiFuSecurity D/AndroidRuntime: Shutting down VM
11-15 16:34:16.411 5130-5130/com.ct.plat.android.ZhiFuSecurity E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.ct.plat.android.ZhiFuSecurity, PID: 5130
                                                                                    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.ct.plat.android.ZhiFuSecurity-1/lib/arm/libAndHook.so"
                                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                                                        at java.lang.System.loadLibrary(System.java:988)
                                                                                        at andhook.lib.AndHook.ensureNativeLibraryLoaded(SourceFile:25)
                                                                                        at andhook.lib.AndHook.<clinit>(SourceFile:21)
                                                                                        at com.ct.util.RunHook.run(SourceFile:78)
                                                                                        at com.ct.plat.android.HexinApplication.attachBaseContext(SourceFile:203)
                                                                                        at android.app.Application.attach(Application.java:181)
                                                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:996)
                                                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:980)
                                                                                        at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
                                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by rrrfff** [comment]
对于模拟器, 你可以打包一个x86版本的so, 检测到libhoudini的情况下加载x86版本的so而不是arm版本的即可

**Comment by bloodNeverCold** [comment]
那 怎样检测模拟器是不是缺少libhoudini？

**Comment by bloodNeverCold** [comment]
魅族手机上 API5.1也报这个信息了

**Comment by rrrfff** [comment]
不是缺少libhoudini, 是存在libhoudini的话需要单独加载x86版本。
魅族是YunOS?

**Comment by bloodNeverCold** [comment]
魅族是YUnOS的 定制的5.1  cpu是 联发科技 Helio X10 64位ARM架构的

**Comment by bloodNeverCold** [comment]
哎前段时间时间使用的是 Legend 在5.1上也崩了 想使用大神你的这个啊

**Comment by rrrfff** [comment]
YunOS闭源定制, 适配难度稍大, 所以并未做兼容

**Comment by bloodNeverCold** [comment]
额 大神能否提供一下  armeabi的so文件 因为项目比较老了 之前导入的so文件只有armeabi 和x86两种形式

**Comment by rrrfff** [comment]
试试直接把v7a的so拷贝过去
