### ISSUE TITLE
Error, please help

### ISSUE THREAD

**Issue by wolfnightblack** [rrrfff/AndHook#23]
Jan 30, 2018 1:08:16 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KOT49H.N900AUCUCMLG' with fingerprint 'samsung/hlteuc/hlteatt:4.4.2/KOT49H/N900AUCUCMLG:user/release-keys'
Loading modules from /data/app/andhook.ui-2.apk
  Loading class andhook.ui.MainHook
java.lang.UnsatisfiedLinkError: incompatible platform, Couldn't load AndHook from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/andhook.ui-2.apk"],nativeLibraryDirectories=[/system/lib, /system/lib/arm, /data/downloads]]]: findLibrary returned null
	at andhook.lib.AndHook.<clinit>(AndHook.java:32)
	at andhook.lib.AndHook$HookHelper.applyHooks(AndHook.java:529)
	at andhook.lib.AndHook$HookHelper.applyHooks(AndHook.java:494)
	at andhook.ui.MainHook.handleLoadPackage(MainHook.java:32)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$2.beforeHookedMethod(XposedBridge.java:228)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at com.android.server.ServerThread.initAndLoop(Native Method)
	at com.android.server.SystemServer.main(SystemServer.java:1204)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
java.lang.NoClassDefFoundError: andhook/lib/AndHook
	at andhook.lib.AndHook$HookHelper.applyHooks(AndHook.java:529)
	at andhook.lib.AndHook$HookHelper.applyHooks(AndHook.java:494)
	at andhook.ui.MainHook.handleLoadPackage(MainHook.java:32)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$3.afterHookedMethod(XposedBridge.java:252)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
	at android.app.LoadedApk.<init>(Native Method)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1647)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1610)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1583)
	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:1894)
	at android.app.ContextImpl.createPackageContext(ContextImpl.java:1880)
	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:637)
	at android.app.ActivityThread.installProvider(ActivityThread.java:4767)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4389)
	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:4949)
	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:8211)
	at com.android.server.ServerThread.initAndLoop(SystemServer.java:278)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at com.android.server.ServerThread.initAndLoop(Native Method)
	at com.android.server.SystemServer.main(SystemServer.java:1204)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by hl46000** [comment]
I think you sai at đoạn này: "java.lang.UnsatisfiedLinkError: incompatible platform, Couldn't load AndHook from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/andhook.ui-2.apk"],nativeLibraryDirectories=[/system/lib, /system/lib/arm, /data/downloads]]]: findLibrary returned null"
Because hệ thống not tìm được folder thư viện.
Sorry for my bad English :)
