### ISSUE TITLE
so加载报错

### ISSUE THREAD

**Issue by ckis** [rrrfff/AndHook#29]
系统是安卓原生7.1.2 SDK:25
由于我的系统有点特殊 所以需要把so文件放在system/lib /lib64下加载
出现以下错误 求解 顺便能否提供一下QQ号呢？非常感谢

incompatible platform, JNI_ERR returned from JNI_OnLoad in "/system/lib64/libAndHook.so"
at andhook.lib.AndHook.<clinit>(AndHook.java:28)
at andhook.lib.AndHook.ensureClassInitialized(AndHook.java:86)
at andhook.lib.xposed.XposedBridge.hookMethod(XposedBridge.java:82)
at com.my.app.HTool.HookMethods(HTool.java:414)
at com.my.app.Main.start_hook_SettingsSecure(Main.java:101)
at com.my.app.Main.main(Main.java:41)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote.InitCKSystem(Zygote.java:204)
at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:255)
at com.android.internal.os.ZygoteConnection.runOnce(ZygoteConnection.java:225)
at com.android.internal.os.ZygoteInit.runSelectLoop(ZygoteInit.java:869)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

**Comment by rrrfff** [comment]
其它错误呢

**Comment by ckis** [comment]
因为SO是闭源的 只抓取到这些错误信息 暂时没办法调试

感觉这套HOOK框架非常出色 想试用一下 可否提供QQ交流的方式呢 会比较方便提交问题

**Comment by rrrfff** [comment]
630235622

**Comment by ckis** [comment]
ok
